#### 1. Згенеруємо матрицю розмірністю **4х5х7** та заповнимо її по випадковому принципу значеннями q_ijk "експертних" оцінок:

In [1]:
import numpy as np

# Розміри матриці
rows = 4
cols = 5
pages = 7

# Генеруємо матрицю A
matrix_A = np.random.uniform(0.2, 1, (pages, rows, cols)).round(2)

# Виводимо матрицю A
print(f"A) 0 <= q_ijk <= 1 \n{matrix_A}\n")

# Створюємо матрицю B, де значення 1, якщо відповідне значення в A > 0.5, і 0 в іншому випадку
matrix_B = (matrix_A > 0.5).astype(int)

# Виводимо матрицю B
print(f"B) q_ijk = {0, 1} \n{matrix_B}\n")

# Оператори умов для призначення значень відповідно до заданих діапазонів
conditions = [
    (matrix_A >= 0) & (matrix_A <= 0.3),
    (matrix_A > 0.3) & (matrix_A <= 0.5),
    (matrix_A > 0.5) & (matrix_A <= 0.7),
    (matrix_A > 0.7) & (matrix_A <= 0.9),
    (matrix_A > 0.9) & (matrix_A <= 1)
]

# Значення, що призначаються відповідно до умов
values = [1, 2, 3, 4, 5]

# Створюємо матрицю C, використовуючи функцію np.select
matrix_C = np.select(conditions, values)

# Виводимо матрицю C
print(f"C) q_ijk = {1, 2, 3, 4, 5} \n{matrix_C}")

# Збереження матриць у файлі для можливого їх перегляду та порівняння
matrices = [matrix_A, matrix_B, matrix_C]
filenames = ["matrix_A.txt", "matrix_B.txt", "matrix_C.txt"]
for matrix, filename in zip(matrices, filenames):
    with open(filename, 'w') as fp:
        print(matrix, file=fp)

A) 0 <= q_ijk <= 1 
[[[0.56 0.99 0.71 0.69 0.27]
  [0.61 0.71 0.68 0.4  0.99]
  [0.7  0.82 0.57 0.94 0.37]
  [0.36 0.93 0.8  0.53 0.8 ]]

 [[0.53 0.4  0.7  0.32 0.24]
  [0.89 0.84 0.71 0.44 0.8 ]
  [0.23 0.34 0.3  0.81 0.66]
  [0.74 0.42 0.7  0.91 0.47]]

 [[0.53 0.33 0.35 0.61 0.52]
  [0.26 0.42 0.27 0.21 0.97]
  [0.99 0.46 0.62 0.75 0.58]
  [0.7  0.64 0.59 0.7  0.73]]

 [[0.43 0.58 0.35 0.77 0.34]
  [0.3  0.86 0.69 0.59 0.56]
  [1.   0.52 0.3  0.84 0.48]
  [0.68 0.82 0.31 0.22 0.21]]

 [[0.61 0.35 0.83 0.99 0.81]
  [0.4  0.5  0.45 0.83 0.47]
  [0.43 0.79 0.26 0.64 0.59]
  [0.69 0.85 0.75 0.36 0.25]]

 [[0.9  0.7  0.58 0.8  0.41]
  [0.73 0.82 0.57 0.42 0.55]
  [0.36 0.82 0.81 0.5  0.79]
  [0.22 0.51 0.52 0.92 0.62]]

 [[0.32 0.71 0.57 0.65 0.37]
  [0.8  0.59 0.4  0.42 0.8 ]
  [0.38 0.89 0.63 0.91 0.51]
  [0.21 0.42 0.72 0.42 0.79]]]

B) q_ijk = (0, 1) 
[[[1 1 1 1 0]
  [1 1 1 0 1]
  [1 1 1 1 0]
  [0 1 1 1 1]]

 [[1 0 1 0 0]
  [1 1 1 0 1]
  [0 0 0 1 1]
  [1 0 1 1 0]]

 [[1 0 0 1 1]
  [0

#### 2. Обчислимо оцінку якості системи захисту інформації, яка описується відповідною матрицею:

##### 2.1. Для матриці C застосуємо звичайну формулу підрахунку середнього арифметичного ↓

In [2]:
# Обчислюємо середнє арифметичне всіх значень матриці C
average_score = np.sum(matrix_C) / (rows * cols * pages)

print("Оцінка якості системи захисту інформації:", round(average_score, 2))

Оцінка якості системи захисту інформації: 2.94


##### 2.2. Для матриці A застосуємо більш досконалу формулу, що враховуватиме вагу кожного елемента ↓

In [3]:
# Задамо матрицю Q
Q = matrix_A

# Таблиця ваг
element_weights = [
    [0.2, 0.15, 0.15, 0.1, 0.05, 0.1, 0.25],
    [0.1, 0.2, 0.3, 0.4],
    [0.15, 0.25, 0.2, 0.1, 0.3]
]

# Розміри матриці Q
num_i, num_j, num_k = Q.shape

# Обчислюємо загальну оцінку
total_quality = 0.0
for k in range(num_k):
    for j in range(num_j):
        for i in range(num_i):
            total_quality += element_weights[2][k] * element_weights[1][j] * element_weights[0][i] * Q[i, j, k]

print("Загальна оцінка якості системи:", round(total_quality, 2))

Загальна оцінка якості системи: 0.61


#### 3. Сформуємо запитання по оцінці якості системи захисту інформації для деяких елементів згідно із **10**-им варіантом:

► **151**
* О1: Нормативно-правова та наукова база;
* H5: Керування системою захисту;
* E1: Виявлення інформації, що підлягає захисту.

▲ **На скільки ефективно наявність нормативно-правової та наукової бази сприяє керуванню системою захисту та виявленню інформації, що підлягає захисту?**

► **457**
* О4: Програмно-технічні засоби;
* H5: Керування системою захисту;
* E7: Здійснення контролю цілісності та керування системою захисту інформації.

▲ **На скільки ефективно програмно-технічні засоби допомагають у здійсненні контролю цілісності та керуванні системою захисту інформації?**

► **417**
* О4: Програмно-технічні засоби;
* H1: Захист об’єктів корпоративних систем;
* E7: Здійснення контролю цілісності та керування системою захисту 
інформації


▲ **На скільки ефективно програмно-технічні засоби забезпечують захист об’єктів корпоративних систем та здійснення контролю цілісності та керування системою захисту інформації?**

► **337**
* О3: Організаційні заходи та правила (політика безпеки);
* H3: Захист каналів зв’язку;
* E7: Здійснення контролю цілісності та керування системою захисту інформації.

▲ **На скільки ефективні організаційні заходи та правила (політика безпеки) сприяють захисту каналів зв’язку та здійсненню контролю цілісності та керуванню системою захисту інформації?**

► **245**
* О2: Структура та завдання органів захисту;
* H4: Придушення побічних електромагнітних випромінювань;
* E5: Вибір засобів захисту інформації та їх характеристик.

▲ **На скільки ефективно структура та завдання органів захисту сприяють придушенню побічних електромагнітних випромінювань та вибору засобів захисту інформації та їх характеристик?**

#### 4. Зробимо висновок, чи можна прийняти КСЗІ, яка характеризується нашою матрицею оцінок:

In [4]:
if total_quality >= 0.75:
    print("КСЗІ можна прийняти до використання, оскільки його загальна оцінка якості більше або дорівнює еталонного значення 0.75! ({:.2} >= 0.75)".format(total_quality))
else:
    print("КСЗІ не можна прийняти до використання, оскільки його загальна оцінка якості менше еталонного значення 0.75! ({:.2} < 0.75)".format(total_quality))

КСЗІ не можна прийняти до використання, оскільки його загальна оцінка якості менше еталонного значення 0.75! (0.61 < 0.75)


#### 5. Обчислимо, які елементи матриці дають найгірший внесок у загальну якість КСЗІ?

In [5]:
# Ініціалізуємо список для збереження найгірших значень внесків матриці
element_contributions = []

# Обчислюємо внесок кожного елементу
for k in range(num_k):
    for j in range(num_j):
        for i in range(num_i):
            element_contribution = element_weights[2][k] * element_weights[1][j] * element_weights[0][i] * Q[i, j, k]
            element_contributions.append((i, j, k, element_contribution))

# Сортуємо елементи за внеском у порядку зростання
sorted_element_contributions = sorted(element_contributions, key=lambda x: x[3])

# Обираємо п'ять елементів із найменшими внесками
top_5_contributions = sorted_element_contributions[:5]

print("Топ-5 елементів із найменшими внесками:")
for value in top_5_contributions:
    i, j, k, contribution = value
    print(f"• ({i}, {j}, {k}) має внесок {round(contribution, 5)}")

Топ-5 елементів із найменшими внесками:
• (4, 0, 1) має внесок 0.00044
• (4, 0, 0) має внесок 0.00046
• (1, 0, 3) має внесок 0.00048
• (4, 0, 3) має внесок 0.0005
• (4, 1, 0) має внесок 0.0006
